name: Synth CDK

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.1.30
    - run: bun install --frozen-lockfile
    - run: bun run cdk synth
